#! /bin/bash  -xue

script_dir=$(readlink -f "$(dirname "$0")")
build_script='build.sh'
rebuild_script='rebuild.sh'

rm -f "${build_script}" "${rebuild_script}"

time  cmake "$@" "${script_dir}" ; echo $?

cat << __EOF__  | tee "${build_script}"
#!/bin/bash  -xue

test_envs=\${TEST_ENVS:-''}
time  make "\$@" && ctest \${test_envs} . ; echo \$?
__EOF__

cat << __EOF__  | tee "${rebuild_script}"
#!/bin/bash  -xue

test_envs=\${TEST_ENVS:-''}
make clean
time  make "\$@" && ctest \${test_envs} . ; echo \$?
__EOF__

chmod 755 "${build_script}" "${rebuild_script}"
